# Generated by Django 5.0.6 on 2024-05-15 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_redditpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='all_awardings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='approved_at_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_css_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_template_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='awarders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='banned_at_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='banned_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='content_categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created_utc',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='discussion_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='distinguished',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='likes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_css_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_text_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='mod_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='mod_reason_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='mod_reason_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='num_reports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='parent_whitelist_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='permalink',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='post_hint',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='preview',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='removed_by_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='report_reasons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='secure_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='secure_media_embed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='selftext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='selftext_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_name_prefixed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_subscribers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='suggested_sort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail_width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='top_awarded_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='treatment_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url_overridden_by_dest',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='whitelist_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
