# Generated by Django 5.0.6 on 2024-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_redditpost_all_awardings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
