# Generated by Django 5.0.6 on 2024-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_redditpost_link_flair_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
