# Generated by Django 5.0.6 on 2024-05-15 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_redditpost_link_flair_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='all_awardings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='allow_live_comments',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='archived',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_flair_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_is_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_patreon_flair',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='author_premium',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='awarders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='can_gild',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='can_mod_post',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='clicked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='contest_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='downs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='edited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='gilded',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='hide_score',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_created_from_ads_ui',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_crosspostable',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_meta',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_original_content',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_reddit_media_domain',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_robot_indexable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_self',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='is_video',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='link_flair_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='locked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='media_only',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='no_follow',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='num_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='num_crossposts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='over_18',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='parent_whitelist_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='permalink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='pinned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='post_hint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='preview',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='pwls',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='quarantine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='saved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='selftext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='send_replies',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='spoiler',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='stickied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_name_prefixed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='total_awards_received',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='ups',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='upvote_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url_overridden_by_dest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='whitelist_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='wls',
            field=models.IntegerField(default=6, null=True),
        ),
    ]
