# Generated by Django 5.0.6 on 2024-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_redditpost_all_awardings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
