# Generated by Django 5.0.6 on 2024-05-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_redditpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='content_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url_overridden_by_dest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
